import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <link href="assets/css/bootstrap.min.css" rel="stylesheet" />
        <link href="assets/css/jquery-ui.css" rel="stylesheet" />
        <link href="assets/css/bootstrap-icons.css" rel="stylesheet" />
        <link href="assets/css/animate.min.css" rel="stylesheet" />
        <link href="assets/css/jquery.fancybox.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="assets/css/swiper-bundle.min.css" />
        <link rel="stylesheet" href="assets/css/slick.css" />
        <link rel="stylesheet" href="assets/css/slick-theme.css" />
        <link rel="stylesheet" href="assets/css/daterangepicker.css" />
        <link href="assets/css/boxicons.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="assets/css/style.css" />
        <title>Gofly - Tour & Travel Booking Website.</title>
        <link rel="icon" href="assets/img/fav-icon.svg" type="image/gif" sizes="20x20" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css"
          integrity="sha512-2SwdPD6INVrV/lHTZbO2nodKhrnDdJK9/kg2XD1r9uGqPo1cUbujc+IYdlYdEErWNu69gVcYgdxlmVmzTWnetw=="
          crossOrigin="anonymous" referrerPolicy="no-referrer" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link
          href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"></link>
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
      <Script data-cfasync="false" src="../../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"/>
      <Script src="assets/js/jquery-3.7.1.min.js"></Script>
      <Script src="assets/js/jquery-ui.js"></Script>
      <Script src="assets/js/moment.min.js"></Script>
      <Script src="assets/js/daterangepicker.min.js"></Script>
      <Script src="assets/js/bootstrap.min.js"></Script>
      <Script src="assets/js/popper.min.js"></Script>
      <Script src="assets/js/swiper-bundle.min.js"></Script>
      <Script src="assets/js/slick.js"></Script>
      <Script src="assets/js/waypoints.min.js"></Script>
      <Script src="assets/js/jquery.counterup.min.js"></Script>
      <Script src="assets/js/wow.min.js"></Script>
      <Script src="assets/js/gsap.min.js"></Script>
      <Script src="assets/js/ScrollTrigger.min.js"></Script>
      <Script src="assets/js/jquery.fancybox.min.js"></Script>
      <Script src="assets/js/select-dropdown.js"></Script>
      <Script src="assets/js/custom.js"></Script>
      <Script defer
        src="https://static.cloudflareinsights.com/beacon.min.js/v8c78df7c7c0f484497ecbca7046644da1771523124516"
        integrity="sha512-8DS7rgIrAmghBFwoOTujcf6D9rXvH8xm8JQ1Ja01h9QX8EzXldiszufYa4IFfKdLUKTTrnSFXLDkUEOTrZQ8Qg=="
        data-cf-beacon='{"version":"2024.11.0","token":"70834e4b23964a2eaf7cf4ec0e5e9a84","r":1,"server_timing":{"name":{"cfCacheStatus":true,"cfEdge":true,"cfExtPri":true,"cfL4":true,"cfOrigin":true,"cfSpeedBrain":true},"location_startswith":null}}'
        crossorigin="anonymous"></Script>
    </html>
  );
}
